title: Seth White's Projects
description:
"[week1](week1.md)  
[week2](week2.md)  
[week3](week3.md)  
[week4](week4.md)  
[week5](week5.md)  
[week6](week6.md)  
[week7](week7.md)  
[week8](week8.md)  
[week9](week9.md)  "
theme: jekyll-theme-time-machine
